// ALLOW STATUS LIST
const STATUS_ALLOWED_VALUES = ['STOP', 'EXIT', 'ONLINE', 'READY', 'ERRORED', 'RESTART', 'RESTART OVERLIMIT'];

// MAPPER STATUS LIST
const STATUS_MAPPER = {
  'STOP': STATUS_ALLOWED_VALUES[0],
  'EXIT': STATUS_ALLOWED_VALUES[1],
  'ONLINE': STATUS_ALLOWED_VALUES[2],
  'READY': STATUS_ALLOWED_VALUES[3],
  'ERRORED': STATUS_ALLOWED_VALUES[4],
  'RESTART': STATUS_ALLOWED_VALUES[2]
}

export { STATUS_ALLOWED_VALUES, STATUS_MAPPER }
